# Generated by Django 2.0.6 on 2018-07-13 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_polls', '0002_auto_20180713_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_polls',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
